name: memoapp            # プロジェクト名
description: A simple sticky todo app   # 任意で説明
publish_to: 'none'              # pub.dev に公開しない場合

version: 0.0.1+1                # version+build number

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+4
  image_cropper: ^9.1.0
  hive: ^2.2.3
  path_provider: ^2.0.14
  file_picker: ^10.1.9
  google_fonts: ^4.0.3
  lottie: ^2.7.0
  url_launcher: ^6.1.12
  #google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/cork_board.jpg
    - assets/text_note_texture.png
    - assets/text_note_fine_paper.png
    - assets/text_note_washi.png
    - assets/text_note_craft.png
    - assets/text_note_woodgrain.png
    #- assets/parchment.jpg
    #- assets/blackboard.jpg
    #- assets/fabric_panel.jpg
    #- assets/wood_panel.jpg